/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atendemeupet.telas;

import br.com.atendemeupet.dao.ServicoDAO;
import br.com.atendemeupet.dao.LojaDAO;
import br.com.atendemeupet.entidades.Servico;
import br.com.atendemeupet.entidades.Loja;
import br.com.atendemeupet.exceptions.EntidadeException;
import br.com.atendemeupet.modelos.ServicoTableModel;
import br.com.atendemeupet.modelos.LojaTableModel;
import br.com.atendemeupet.util.JpaUtil;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Rafael Vieira
 */
public class CadastroServicoLoja extends javax.swing.JInternalFrame {

    private static CadastroServicoLoja cadastroServicoLoja;
    private LojaDAO ldao = new LojaDAO(JpaUtil.getEM());
    private ServicoDAO sdao = new ServicoDAO(JpaUtil.getEM());
    private List<Loja> listaLojas = ldao.listarLojas();
    private List<Servico> listaServicos = sdao.listarServicos();
    private LojaTableModel modeloLoja = new LojaTableModel(listaLojas);
    private ServicoTableModel modeloServico = new ServicoTableModel(listaServicos);

    private CadastroServicoLoja() {
        initComponents();
    }

    @Override
    public void dispose() {
        cadastroServicoLoja = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    public static synchronized CadastroServicoLoja getInstance() {
        if (cadastroServicoLoja == null) {
            cadastroServicoLoja = new CadastroServicoLoja();
        }
        return cadastroServicoLoja;
    }

    private void limpar(List<JComponent> unit) {
        for (JComponent jComponent : unit) {
            if (jComponent instanceof JTextField) {
                ((JTextField) jComponent).setText(null);
            }

            if (jComponent instanceof JFormattedTextField) {
                ((JFormattedTextField) jComponent).setValue(null);
                ((JFormattedTextField) jComponent).setText(null);
            }
        }
    }

    private void continuar() {
        OUTER:
        while (true) {
            String resposta = JOptionPane.showInputDialog("Deseja continuar ? [S/N]");

            if (resposta == null) {
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
                dispose();
                break;
            }

            switch (resposta) {
                case "S":
                    modeloLoja = new LojaTableModel(listaLojas);
                    tabelaLoja.setModel(modeloLoja);
                    modeloServico = new ServicoTableModel(listaServicos);
                    tabelaServico.setModel(modeloServico);
                    limpar(Arrays.asList(nomeLoja, tipoServico));
                    break OUTER;
                case "N":
                    JOptionPane.showMessageDialog(null, "Operação cancelada!");
                    dispose();
                    break OUTER;
                default:
                    JOptionPane.showMessageDialog(null, "Opção inválida! - Tente usar S ou N.");

            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaLoja = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        nomeLoja = new javax.swing.JTextField();
        buscarLoja = new javax.swing.JButton();
        cadastrar = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tipoServico = new javax.swing.JTextField();
        buscarServico = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabelaServico = new javax.swing.JTable();

        setClosable(true);
        setResizable(true);
        setTitle("Cadastro de Serviço na Loja");

        tabelaLoja.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabelaLoja.setModel(modeloLoja);
        tabelaLoja.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabelaLoja);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("LOJA: ");

        buscarLoja.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buscarLoja.setText("BUSCAR");
        buscarLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarLojaActionPerformed(evt);
            }
        });

        cadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        cadastrar.setText("CADASTRAR");
        cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadastrarActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("SERVIÇO: ");

        buscarServico.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        buscarServico.setText("BUSCAR");
        buscarServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarServicoActionPerformed(evt);
            }
        });

        tabelaServico.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabelaServico.setModel(modeloServico);
        tabelaServico.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane2.setViewportView(tabelaServico);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(nomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(buscarLoja))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(buscarServico))
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(26, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(145, 145, 145))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(nomeLoja, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarLoja))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tipoServico, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buscarServico))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addComponent(cadastrar)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buscarLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarLojaActionPerformed
        // TODO add your handling code here:
        if (!nomeLoja.getText().isEmpty()) {
            List<Loja> aux = ldao.listarLojas(nomeLoja.getText());

            if (!aux.isEmpty()) {
                modeloLoja = new LojaTableModel(aux);
                tabelaLoja.setModel(modeloLoja);
            } else {
                JOptionPane.showMessageDialog(null, "Loja " + nomeLoja.getText() + " não foi encontrada!");
                nomeLoja.setText(null);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Verifique o campo antes de tentar realizar uma busca!");
        }

    }//GEN-LAST:event_buscarLojaActionPerformed

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        if (tabelaLoja.getSelectedRow() != -1 && tabelaServico.getSelectedRow() != -1) {
            Loja loja = modeloLoja.getRow(tabelaLoja.getSelectedRow());
            Servico servico = modeloServico.getRow(tabelaServico.getSelectedRow());

            if (loja.getServicos() == null) {
                List<Servico> servicos = new ArrayList<>();
                servicos.add(servico);
                loja.setServicos(servicos);

            } else {
                while (true) {
                    try {
                        for (Servico serv : loja.getServicos()) {
                            if (servico.equals(serv)) {
                                throw new EntidadeException("Essa loja já possui esse serviço cadastrado!");
                            }
                        }

                        loja.getServicos().add(servico);
                        break;

                    } catch (EntidadeException e) {
                        JOptionPane.showMessageDialog(null, e.getMessage());
                        continuar();
                        return;

                    }
                }

            }

            if (servico.getLojas() == null) {
                List<Loja> lojas = new ArrayList<>();
                lojas.add(loja);
                servico.setLojas(lojas);
            } else {
                servico.getLojas().add(loja);
            }

            ldao.atualizarLoja(loja);
            sdao.atualizarServico(servico);

            JOptionPane.showMessageDialog(null, "Operações realizadas com sucesso!");
            continuar();

        } else {
            JOptionPane.showMessageDialog(null, "Selecione uma loja e/ou um serviço primeiro!");
        }


    }//GEN-LAST:event_cadastrarActionPerformed

    private void buscarServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarServicoActionPerformed
        // TODO add your handling code here:
        if (!tipoServico.getText().isEmpty()) {
            List<Servico> aux = sdao.listarServicos(tipoServico.getText());

            if (!aux.isEmpty()) {
                modeloServico = new ServicoTableModel(aux);
                tabelaServico.setModel(modeloServico);
            } else {
                JOptionPane.showMessageDialog(null, "Serviço " + tipoServico.getText() + " não foi encontrado!");
                tipoServico.setText(null);
            }

        } else {
            JOptionPane.showMessageDialog(null, "Verifique o campo antes de tentar realizar uma busca!");
        }
    }//GEN-LAST:event_buscarServicoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscarLoja;
    private javax.swing.JButton buscarServico;
    private javax.swing.JButton cadastrar;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField nomeLoja;
    private javax.swing.JTable tabelaLoja;
    private javax.swing.JTable tabelaServico;
    private javax.swing.JTextField tipoServico;
    // End of variables declaration//GEN-END:variables
}
