/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atendemeupet.telas;

import br.com.atendemeupet.dao.LojaDAO;
import br.com.atendemeupet.entidades.Loja;
import br.com.atendemeupet.exceptions.CampoException;
import br.com.atendemeupet.exceptions.EntidadeException;
import br.com.atendemeupet.util.JpaUtil;
import java.text.ParseException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Rafael Vieira
 */
public class CadastroLoja extends javax.swing.JInternalFrame {

    private static CadastroLoja cadastroLoja;

    private LojaDAO dao = new LojaDAO(JpaUtil.getEM());

    @Override
    public void dispose() {
        cadastroLoja = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    private void limpar(List<JComponent> unit) {
        for (JComponent jComponent : unit) {
            if (jComponent instanceof JTextField) {
                ((JTextField) jComponent).setText(null);
            }

            if (jComponent instanceof JFormattedTextField) {
                ((JFormattedTextField) jComponent).setValue(null);
                ((JFormattedTextField) jComponent).setText(null);
            }
        }
    }

    private void continuar() {
        OUTER:
        while (true) {
            String resposta = JOptionPane.showInputDialog("Deseja continuar cadastrando? [S/N]");

            if (resposta == null) {
                JOptionPane.showMessageDialog(null, "Operação cancelada!");
                dispose();
                break;
            }

            switch (resposta) {
                case "S":
                    limpar(Arrays.asList(razaoSocial, cnpj));
                    break OUTER;
                case "N":
                    JOptionPane.showMessageDialog(null, "Operação cancelada!");
                    dispose();
                    break OUTER;
                default:
                    JOptionPane.showMessageDialog(null, "Opção inválida! - Tente usar S ou N.");

            }
        }
    }

    private CadastroLoja() {
        initComponents();

    }

    public static CadastroLoja getInstance() {
        if (cadastroLoja == null) {
            cadastroLoja = new CadastroLoja();
        }
        return cadastroLoja;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();
        cadastrar = new javax.swing.JButton();
        razaoSocial = new javax.swing.JTextField();

        setClosable(true);
        setTitle("Cadastro de Loja");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("CNPJ: ");

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("RAZÃO SOCIAL: ");

        try {
            cnpj.setFormatterFactory(new DefaultFormatterFactory(
                new MaskFormatter("##.###.###/####-##")));
    } catch (ParseException e) {
        e.printStackTrace();
    }
    cnpj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cnpjActionPerformed(evt);
        }
    });

    cadastrar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
    cadastrar.setText("CADASTRAR");
    cadastrar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cadastrarActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(29, 29, 29)
                            .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(64, 64, 64)
                    .addComponent(cadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addContainerGap(37, Short.MAX_VALUE))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(32, 32, 32)
            .addComponent(jLabel5)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addComponent(razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(30, 30, 30)
            .addComponent(jLabel1)
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(46, 46, 46)
            .addComponent(cadastrar)
            .addContainerGap(51, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadastrarActionPerformed
        // TODO add your handling code here:
        try {
            if (razaoSocial.getText().length() < 5 || razaoSocial.getText().isEmpty()) {
                razaoSocial.setText(null);
                throw new CampoException("Verifique o campo: Razão Social !");
            }

            if (cnpj.getValue() == null) {
                cnpj.setValue(null);
                throw new CampoException("Verifique o campo: CNPJ !");
            }

           

            Loja loja = new Loja(razaoSocial.getText(), (String)cnpj.getValue());

            List<Loja> listaLojas = dao.listarLojas();

            if (listaLojas.isEmpty()) {
                dao.inserirLoja(loja);
                JOptionPane.showMessageDialog(null, "Loja Cadastrada com sucesso! ");
                continuar();
            } else {
                for (Loja listaLoja : listaLojas) {
                    if (loja.equals(listaLoja)) {
                        throw new EntidadeException("Essa Loja já foi cadastrada!");
                    }
                }
                dao.inserirLoja(loja);
                JOptionPane.showMessageDialog(null, "Loja Cadastrada com sucesso! ");
                continuar();

            }

        } catch (CampoException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
        } catch (EntidadeException e) {
            JOptionPane.showMessageDialog(null, e.getMessage());
            continuar();
        }

    }//GEN-LAST:event_cadastrarActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cadastrar;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField razaoSocial;
    // End of variables declaration//GEN-END:variables

}
