/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atendemeupet.telas;

import br.com.atendemeupet.dao.UsuarioDAO;
import br.com.atendemeupet.entidades.Usuario;
import br.com.atendemeupet.modelos.UsuarioTableModel;
import br.com.atendemeupet.util.JpaUtil;
import java.text.ParseException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Rafael Vieira
 */
public class EditarUsuario extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarUsuario
     */
    private static EditarUsuario editarUsuario;

    private UsuarioDAO dao = new UsuarioDAO(JpaUtil.getEM());
    private List<Usuario> listaUsuarios = dao.listarUsuarios();
    private UsuarioTableModel modelo = new UsuarioTableModel(listaUsuarios);

    private EditarUsuario() {
        initComponents();

    }

    public static synchronized EditarUsuario getInstance() {
        if (editarUsuario == null) {
            editarUsuario = new EditarUsuario();
        }
        return editarUsuario;
    }

    @Override
    public void dispose() {
//        limpar(Arrays.asList(nome, endereco, cidade, cep, email, telefone));
        editarUsuario = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }

    private void limpar(List<JComponent> unit) {
        for (JComponent jComponent : unit) {
            if (jComponent instanceof JTextField) {
                ((JTextField) jComponent).setText(null);
            }

            if (jComponent instanceof JFormattedTextField) {
                ((JFormattedTextField) jComponent).setValue(null);
                ((JFormattedTextField) jComponent).setText(null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        nome = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        endereco = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        cidade = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        telefone = new javax.swing.JFormattedTextField();
        cep = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Editar Usuário");
        setToolTipText("");

        alterar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        alterar.setText("ALTERAR USUÁRIO");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        excluir.setText("EXCLUIR USUÁRIO");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabela.setModel(modelo);
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabela);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("NOME:");

        jLabel4.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel4.setText("E-MAIL:");

        email.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                emailActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel6.setText("ENDEREÇO: ");

        jLabel7.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel7.setText("CIDADE: ");

        jLabel8.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel8.setText("CEP:");

        jLabel9.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel9.setText("TELEFONE: ");

        try {
            telefone.setFormatterFactory(new DefaultFormatterFactory(
                new MaskFormatter("(##)#####-####")));
    } catch (ParseException e) {
        e.printStackTrace();
    }
    telefone.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            telefoneActionPerformed(evt);
        }
    });

    try {
        cep.setFormatterFactory(new DefaultFormatterFactory(
            new MaskFormatter("#####-###")));
    } catch (ParseException e) {
        e.printStackTrace();
    }

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 644, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(299, 299, 299)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addComponent(jLabel6)
                    .addGap(88, 88, 88)
                    .addComponent(jLabel7)
                    .addGap(64, 64, 64)
                    .addComponent(jLabel8)
                    .addGap(135, 135, 135)
                    .addComponent(jLabel9))
                .addGroup(layout.createSequentialGroup()
                    .addGap(10, 10, 10)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, 252, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(112, 112, 112)
                            .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, 253, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(10, 10, 10)
                            .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(113, 113, 113)
                    .addComponent(alterar)
                    .addGap(137, 137, 137)
                    .addComponent(excluir)))
            .addGap(10, 10, 10))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(26, 26, 26)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(11, 11, 11)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5)
                .addComponent(jLabel4))
            .addGap(11, 11, 11)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(email, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel6)
                .addComponent(jLabel7)
                .addComponent(jLabel8)
                .addComponent(jLabel9))
            .addGap(11, 11, 11)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(cep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(telefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(alterar)
                .addComponent(excluir))
            .addGap(24, 24, 24))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1 && !listaUsuarios.isEmpty()) {
            dao.removerUsuario(modelo.removeRow(tabela.getSelectedRow()));
            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhum cliente cadastrado!");
        }

    }//GEN-LAST:event_excluirActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:

        if (tabela.getSelectedRow() != -1 && !listaUsuarios.isEmpty()) {
            boolean verificar = false;
            Usuario modificado;
            modificado = listaUsuarios.get(tabela.getSelectedRow());

            if (nome.getText().length() >= 5) {
                modificado.setNome(nome.getText());
                modelo.setValueAt(nome.getText(), tabela.getSelectedRow(), 1);
                verificar = true;

            }

            if (telefone.getValue() != null) {
                modificado.setTelefone((String) telefone.getValue());
                modelo.setValueAt(telefone.getValue(), tabela.getSelectedRow(), 3);
                verificar = true;
            }

            if (email.getText().length() >= 5) {
                modificado.setEmail(email.getText());
                modelo.setValueAt(email.getText(), tabela.getSelectedRow(), 4);
                verificar = true;
            }

            if (endereco.getText().length() >= 5) {
                modificado.getEndereco().setEndereco(endereco.getText());
                modelo.setValueAt(endereco.getText(), tabela.getSelectedRow(), 5);
                verificar = true;
            }

            if (cidade.getText().length() >= 5) {
                modificado.getEndereco().setCidade(cidade.getText());
                modelo.setValueAt(cidade.getText(), tabela.getSelectedRow(), 6);
                verificar = true;
            }

            if (cep.getValue() != null) {
                modificado.getEndereco().setCep((String) cep.getValue());
                modelo.setValueAt(cep.getValue(), tabela.getSelectedRow(), 7);
                verificar = true;
            }

            if (verificar) {
                dao.atualizarUsuario(modificado);
                limpar(Arrays.asList(nome, endereco, cidade, cep, email, telefone));
                JOptionPane.showMessageDialog(null, "Alteração(ões) realizada(s) com sucesso !");
                
            }else{
                limpar(Arrays.asList(nome, endereco, cidade, cep, email, telefone));
                JOptionPane.showMessageDialog(null, "Verifique os campos antes de tentar alterar!");
            }

        }else {
            JOptionPane.showMessageDialog(null, "Verifique se existe ou foi selecionado algum cliente!");
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void emailActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_emailActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_emailActionPerformed

    private void telefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefoneActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JFormattedTextField cep;
    private javax.swing.JTextField cidade;
    private javax.swing.JTextField email;
    private javax.swing.JTextField endereco;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nome;
    private javax.swing.JTable tabela;
    private javax.swing.JFormattedTextField telefone;
    // End of variables declaration//GEN-END:variables

}
