/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atendemeupet.telas;

import br.com.atendemeupet.dao.LojaDAO;
import br.com.atendemeupet.dao.ServicoDAO;
import br.com.atendemeupet.entidades.Loja;
import br.com.atendemeupet.entidades.Servico;
import br.com.atendemeupet.modelos.LojaTableModel;
import br.com.atendemeupet.util.JpaUtil;
import java.text.ParseException;
import java.util.Arrays;
import java.util.List;
import javax.swing.JComponent;
import javax.swing.JFormattedTextField;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.text.DefaultFormatterFactory;
import javax.swing.text.MaskFormatter;

/**
 *
 * @author Rafael Vieira
 */
public class EditarLoja extends javax.swing.JInternalFrame {

    /**
     * Creates new form EditarLoja
     */
    private static EditarLoja editarLoja;
    
    private LojaDAO dao = new LojaDAO(JpaUtil.getEM());
    private List<Loja> listaLojas = dao.listarLojas();
    private LojaTableModel modelo = new LojaTableModel(listaLojas);
    
    private EditarLoja() {
        initComponents();
        
    }
    
    public static synchronized EditarLoja getInstance() {
        if (editarLoja == null) {
            editarLoja = new EditarLoja();
        }
        return editarLoja;
    }
    
    @Override
    public void dispose() {
        editarLoja = null;
        super.dispose(); //To change body of generated methods, choose Tools | Templates.
    }
    
    private void limpar(List<JComponent> unit) {
        for (JComponent jComponent : unit) {
            if (jComponent instanceof JTextField) {
                ((JTextField) jComponent).setText(null);
            }
            
            if (jComponent instanceof JFormattedTextField) {
                ((JFormattedTextField) jComponent).setValue(null);
                ((JFormattedTextField) jComponent).setText(null);
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        alterar = new javax.swing.JButton();
        excluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        razaoSocial = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        cnpj = new javax.swing.JFormattedTextField();

        setClosable(true);
        setTitle("Editar Loja");
        setToolTipText("");

        alterar.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        alterar.setText("ALTERAR LOJA");
        alterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarActionPerformed(evt);
            }
        });

        excluir.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        excluir.setText("EXCLUIR LOJA");
        excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirActionPerformed(evt);
            }
        });

        tabela.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N
        tabela.setModel(modelo);
        tabela.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tabela);

        jLabel5.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel5.setText("RAZÃO SOCIAL: ");

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 1, 14)); // NOI18N
        jLabel1.setText("CNPJ: ");

        try {
            cnpj.setFormatterFactory(new DefaultFormatterFactory(
                new MaskFormatter("##.###.###/####-##")));
    } catch (ParseException e) {
        e.printStackTrace();
    }
    cnpj.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cnpjActionPerformed(evt);
        }
    });

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGap(19, 19, 19)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(0, 0, Short.MAX_VALUE))
        .addGroup(layout.createSequentialGroup()
            .addGap(67, 67, 67)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(alterar))
            .addGap(81, 81, 81)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(154, Short.MAX_VALUE))
                .addGroup(layout.createSequentialGroup()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(excluir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cnpj))
                    .addGap(65, 65, 65))))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel5)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(razaoSocial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jLabel1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addComponent(cnpj, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
            .addGap(18, 18, 18)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(alterar)
                .addComponent(excluir))
            .addContainerGap(21, Short.MAX_VALUE))
    );

    pack();
    }// </editor-fold>//GEN-END:initComponents

    private void excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirActionPerformed
        // TODO add your handling code here:
        if (tabela.getSelectedRow() != -1 && !listaLojas.isEmpty()) {
            ServicoDAO sdao = new ServicoDAO(JpaUtil.getEM());
            Loja loja = modelo.removeRow(tabela.getSelectedRow());
            
            for (Servico servico : loja.getServicos()) {
                servico.getLojas().remove(loja);
                sdao.atualizarServico(servico);
            }
            
            dao.removerLoja(loja);
            JOptionPane.showMessageDialog(null, "Exclusão realizada com sucesso!");
        } else {
            JOptionPane.showMessageDialog(null, "Nenhuma Loja cadastrada!");
        }

    }//GEN-LAST:event_excluirActionPerformed

    private void alterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarActionPerformed
        // TODO add your handling code here:

        if (tabela.getSelectedRow() != -1 && !listaLojas.isEmpty()) {
            boolean verificar = false;
            Loja modificado;
            modificado = listaLojas.get(tabela.getSelectedRow());
            
            if (!razaoSocial.getText().isEmpty()) {
                modificado.setRazaoSocial(razaoSocial.getText());
                modelo.setValueAt(razaoSocial.getText(), tabela.getSelectedRow(), 1);
                verificar = true;
                
            }
            
            if(cnpj.getValue() != null){
                modificado.setCnpj((String)cnpj.getValue());
                modelo.setValueAt((String)cnpj.getValue(), tabela.getSelectedRow(), 2);
                verificar = true;
            }
            
            if (verificar) {
                dao.atualizarLoja(modificado);
                limpar(Arrays.asList(razaoSocial, cnpj));
                JOptionPane.showMessageDialog(null, "Alteração(ões) realizada(s) com sucesso !");
                
            } else {
                limpar(Arrays.asList(razaoSocial, cnpj));
                JOptionPane.showMessageDialog(null, "Verifique os campos antes de tentar alterar!");
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Verifique se existe ou foi selecionado algum loja!");
        }
    }//GEN-LAST:event_alterarActionPerformed

    private void cnpjActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cnpjActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cnpjActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton alterar;
    private javax.swing.JFormattedTextField cnpj;
    private javax.swing.JButton excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField razaoSocial;
    private javax.swing.JTable tabela;
    // End of variables declaration//GEN-END:variables

}
