/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.atendemeupet.telas;

import br.com.atendemeupet.dao.LojaDAO;
import br.com.atendemeupet.dao.PetDAO;
import br.com.atendemeupet.dao.ReservaDAO;
import br.com.atendemeupet.dao.ServicoDAO;
import br.com.atendemeupet.dao.UsuarioDAO;
import br.com.atendemeupet.util.JpaUtil;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Rafael Vieira
 */
public class Tela extends javax.swing.JFrame {

    private UsuarioDAO usuarioDAO = new UsuarioDAO(JpaUtil.getEM());
    private PetDAO petDAO = new PetDAO(JpaUtil.getEM());
    private LojaDAO lojaDAO = new LojaDAO(JpaUtil.getEM());
    private ServicoDAO servicoDAO = new ServicoDAO(JpaUtil.getEM());
    private ReservaDAO reservaDAO = new ReservaDAO(JpaUtil.getEM());

    /**
     * Creates new form Tela
     */
    public Tela() {
        initComponents();
        setIcon();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ImageIcon icon  = new ImageIcon(getClass().getResource("doguinho.jpg"));
        Image image =  icon.getImage();
        painelPrincipal = new javax.swing.JDesktopPane(){

            public void paintComponent(Graphics g){
                g.drawImage(image, 0, 0, getWidth(),getHeight(),this);
            }

        };
        menu = new javax.swing.JMenuBar();
        jCadastro = new javax.swing.JMenu();
        jCadastroUsuario = new javax.swing.JMenuItem();
        jCadastroPet = new javax.swing.JMenuItem();
        jCadastroServico = new javax.swing.JMenuItem();
        jCadastroLoja = new javax.swing.JMenuItem();
        jCadastroServicoLoja = new javax.swing.JMenuItem();
        jEdicao = new javax.swing.JMenu();
        jEdicaoUsuario = new javax.swing.JMenuItem();
        jEdicaoPet = new javax.swing.JMenuItem();
        jEdicaoServico = new javax.swing.JMenuItem();
        jEdicaoLoja = new javax.swing.JMenuItem();
        jReserva = new javax.swing.JMenu();
        jCadastroReserva = new javax.swing.JMenuItem();
        jRelatorio = new javax.swing.JMenu();
        jGerarRelatorio = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setTitle("AtendeMeuPet!");
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });

        javax.swing.GroupLayout painelPrincipalLayout = new javax.swing.GroupLayout(painelPrincipal);
        painelPrincipal.setLayout(painelPrincipalLayout);
        painelPrincipalLayout.setHorizontalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 763, Short.MAX_VALUE)
        );
        painelPrincipalLayout.setVerticalGroup(
            painelPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );

        menu.setBorder(null);
        menu.setFont(new java.awt.Font("Trebuchet MS", 1, 12)); // NOI18N

        jCadastro.setText("Cadastro");

        jCadastroUsuario.setText("Cadastrar Usuário");
        jCadastroUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroUsuarioActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroUsuario);

        jCadastroPet.setText("Cadastrar Pet");
        jCadastroPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroPetActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroPet);

        jCadastroServico.setText("Cadastrar Serviço");
        jCadastroServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroServicoActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroServico);

        jCadastroLoja.setText("Cadastrar Loja");
        jCadastroLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroLojaActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroLoja);

        jCadastroServicoLoja.setText("Cadastrar Servicos na Loja");
        jCadastroServicoLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroServicoLojaActionPerformed(evt);
            }
        });
        jCadastro.add(jCadastroServicoLoja);

        menu.add(jCadastro);

        jEdicao.setText("Edição");

        jEdicaoUsuario.setText("Editar Usuário");
        jEdicaoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdicaoUsuarioActionPerformed(evt);
            }
        });
        jEdicao.add(jEdicaoUsuario);

        jEdicaoPet.setText("Editar Pet");
        jEdicaoPet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdicaoPetActionPerformed(evt);
            }
        });
        jEdicao.add(jEdicaoPet);

        jEdicaoServico.setText("Editar Serviço");
        jEdicaoServico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdicaoServicoActionPerformed(evt);
            }
        });
        jEdicao.add(jEdicaoServico);

        jEdicaoLoja.setText("Editar Loja");
        jEdicaoLoja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jEdicaoLojaActionPerformed(evt);
            }
        });
        jEdicao.add(jEdicaoLoja);

        menu.add(jEdicao);

        jReserva.setText("Reservas");

        jCadastroReserva.setText("Criar Reserva");
        jCadastroReserva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCadastroReservaActionPerformed(evt);
            }
        });
        jReserva.add(jCadastroReserva);

        menu.add(jReserva);

        jRelatorio.setText("Relatórios");

        jGerarRelatorio.setText("Gerar Relatório de Reservas");
        jGerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jGerarRelatorioActionPerformed(evt);
            }
        });
        jRelatorio.add(jGerarRelatorio);

        menu.add(jRelatorio);

        setJMenuBar(menu);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(painelPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
        // TODO add your handling code here:
        JpaUtil.getEM().close();
        JpaUtil.getFACTORY().close();
        System.exit(0);
    }//GEN-LAST:event_formWindowClosing

    private void jCadastroUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroUsuarioActionPerformed
        // TODO add your handling code here:
        if (!CadastroUsuario.getInstance().isVisible()) {
            painelPrincipal.add(CadastroUsuario.getInstance());
            CadastroUsuario.getInstance().setVisible(true);
        }
    }//GEN-LAST:event_jCadastroUsuarioActionPerformed

    private void jCadastroLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroLojaActionPerformed
        // TODO add your handling code here:
        if (!CadastroLoja.getInstance().isVisible()) {
            painelPrincipal.add(CadastroLoja.getInstance());
            CadastroLoja.getInstance().setVisible(true);
        }
    }//GEN-LAST:event_jCadastroLojaActionPerformed

    private void jCadastroPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroPetActionPerformed
        // TODO add your handling code here:
        if (usuarioDAO.listarUsuarios().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum usuário foi cadastrado!");

        } else {
            if (!CadastroPet.getInstance().isVisible()) {
                painelPrincipal.add(CadastroPet.getInstance());
                CadastroPet.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jCadastroPetActionPerformed

    private void jCadastroServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroServicoActionPerformed
        // TODO add your handling code here:
        if (!CadastroServico.getInstance().isVisible()) {
            painelPrincipal.add(CadastroServico.getInstance());
            CadastroServico.getInstance().setVisible(true);
        }
    }//GEN-LAST:event_jCadastroServicoActionPerformed

    private void jCadastroServicoLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroServicoLojaActionPerformed
        // TODO add your handling code here:
        if (lojaDAO.listarLojas().isEmpty() || servicoDAO.listarServicos().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma loja ou serviço foram cadastrados!");
        } else {
            if (!CadastroServicoLoja.getInstance().isVisible()) {
                painelPrincipal.add(CadastroServicoLoja.getInstance());
                CadastroServicoLoja.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jCadastroServicoLojaActionPerformed

    private void jEdicaoUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdicaoUsuarioActionPerformed
        // TODO add your handling code here:
        if (usuarioDAO.listarUsuarios().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum usuário foi cadastrado!");

        } else {
            if (!EditarUsuario.getInstance().isVisible()) {
                painelPrincipal.add(EditarUsuario.getInstance());
                EditarUsuario.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jEdicaoUsuarioActionPerformed

    private void jEdicaoPetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdicaoPetActionPerformed
        // TODO add your handling code here:
         if (petDAO.listarPets().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum pet foi cadastrado!");

        } else {
            if (!EditarPet.getInstance().isVisible()) {
                painelPrincipal.add(EditarPet.getInstance());
                EditarPet.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jEdicaoPetActionPerformed

    private void jEdicaoServicoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdicaoServicoActionPerformed
        // TODO add your handling code here:
         if (servicoDAO.listarServicos().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhum serviço foi cadastrado!");

        } else {
            if (!EditarServico.getInstance().isVisible()) {
                painelPrincipal.add(EditarServico.getInstance());
                EditarServico.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jEdicaoServicoActionPerformed

    private void jEdicaoLojaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jEdicaoLojaActionPerformed
        // TODO add your handling code here:
         if (lojaDAO.listarLojas().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma loja foi cadastrada!");

        } else {
            if (!EditarLoja.getInstance().isVisible()) {
                painelPrincipal.add(EditarLoja.getInstance());
                EditarLoja.getInstance().setVisible(true);
            }
        }
        
    }//GEN-LAST:event_jEdicaoLojaActionPerformed

    private void jCadastroReservaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCadastroReservaActionPerformed
        // TODO add your handling code here:
        if (lojaDAO.listarLojasServicos().isEmpty() ||usuarioDAO.listarUsuariosPets().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Cadastros de lojas e/ou usuários incompletos!");

        } else {
            if (!CadastroReserva.getInstance().isVisible()) {
                painelPrincipal.add(CadastroReserva.getInstance());
                CadastroReserva.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jCadastroReservaActionPerformed

    private void jGerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jGerarRelatorioActionPerformed
        // TODO add your handling code here:
         if (reservaDAO.listarReservas().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nenhuma reserva foi cadastrada !");

        } else {
            if (!Relatorios.getInstance().isVisible()) {
                painelPrincipal.add(Relatorios.getInstance());
                Relatorios.getInstance().setVisible(true);
            }
        }
    }//GEN-LAST:event_jGerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela().setVisible(true);
            }
        });
    }

    private void setIcon() {
        setIconImage(Toolkit.getDefaultToolkit().getImage(getClass().getResource("icon.png")));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jCadastro;
    private javax.swing.JMenuItem jCadastroLoja;
    private javax.swing.JMenuItem jCadastroPet;
    private javax.swing.JMenuItem jCadastroReserva;
    private javax.swing.JMenuItem jCadastroServico;
    private javax.swing.JMenuItem jCadastroServicoLoja;
    private javax.swing.JMenuItem jCadastroUsuario;
    private javax.swing.JMenu jEdicao;
    private javax.swing.JMenuItem jEdicaoLoja;
    private javax.swing.JMenuItem jEdicaoPet;
    private javax.swing.JMenuItem jEdicaoServico;
    private javax.swing.JMenuItem jEdicaoUsuario;
    private javax.swing.JMenuItem jGerarRelatorio;
    private javax.swing.JMenu jRelatorio;
    private javax.swing.JMenu jReserva;
    private javax.swing.JMenuBar menu;
    private javax.swing.JDesktopPane painelPrincipal;
    // End of variables declaration//GEN-END:variables
}
